### ISSUE TITLE
Support strings

### ISSUE THREAD

**Issue by florence** [lexi-lambda/racket-alexis-collections#1]
I find myself doing sequence-like operations on strings a lot (Especially for text-rending like operations). It would be nice if strings were sequences in this library.

**Comment by florence** [comment]
Both strings and byte-strings would be nice actually :)

**Comment by lexi-lambda** [comment]
Yes, I agree. I think the right approach is to make strings and bytestrings sequences but not collections, then provide `sequence->string` and `sequence->bytes` functions with `(sequenceof char?)` and `(sequenceof byte?)` contracts, respectively. Does that sound reasonable?

**Comment by florence** [comment]
That sounds good to me. Probably want to keep in mind that Both strings and bytes have mutable and immutable variants (ug).

**Comment by lexi-lambda** [comment]
Added in ac6627a8bb04a92c8b063fe5b2aebd535c1cf490.
