### ISSUE TITLE
Add a match pattern for sequences

### ISSUE THREAD

**Issue by florence** [lexi-lambda/racket-alexis-collections#2]
So I can do things like:

```
(match-define (sequence a b c) <some-bizzare-lazy-sequence-ive-built-up>)
```

This is probably tricky because the pattern `(sequence a b c ...)` should probably have `c` bound to a lazy sequence, and the pattern `(sequence a b ... c)` should require something that is known to be finite...

Or I can just keep using `sequence->list` and `list` pattern. Thats probably less work...

**Comment by lexi-lambda** [comment]
Added a `sequence` match expander in f56d05f8db63ec9e4710b2d3535793a9eab10a9e.
