### ISSUE TITLE
conj on streams, or the result of append?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-alexis-collections#6]
I'm trying to use generic collections in a program, and I have code like

``` racket
;; search-for-shape : Shape Pos Pos-Real -> (Finite-Sequenceof Shape)
;; returns a sequence of the shapes within a radius r of pos
(define (search-for-shape shape pos r)
  (define deps-search-results (append-map (search-for-shape _ pos r) (get-deps shape)))
  (cond [(contains-pos? shape pos r)
         (conj deps-search-results shape)]
        [else
         deps-search-results]))
```

But `append-map` is returning a stream and `conj` can't take streams.
Should streams be added to `gen:collection`, or should `append` and `append-map` return `(and/c sequence? collection?)` values?

**Comment by lexi-lambda** [comment]
Yes, streams should be `collection?`s—the result of `append`, however, shouldn't need to be. I wouldn't necessarily rely on `append` returning a collection... I'm not sure how I want to handle this right now. I've thought about it before, but I haven't come up with a satisfying answer. Maybe `sequence?`s should be converted to streams when used as collections? That seems like poor behavior, though.

**Comment by AlexKnauth** [comment]
Should there be a `sequence->collection` function for this then?

**Comment by lexi-lambda** [comment]
No because a sequence can be lots of different kinds of collections—we shouldn't provide a `sequence->collection` function and assume for the user what kind of collection they want. There's already `sequence->list` if you want that. Otherwise, just use `extend`. The proper way to convert between sequence types is `(extend empty-seq other-seq)`; for example, to convert a sequence to a vector, you'd use `(extend #() seq)`.

**Comment by AlexKnauth** [comment]
I mean a function that returns some implementation, it doesn't matter what, that implements both gen:sequence and gen:collection. The problem with sequence->list is that it doesn't work with potentially infinite sequences. `(extend empty-seq other-seq)` would do what I want, but it would mean that it would have to be remade for every type of sequence.

**Comment by lexi-lambda** [comment]
I would be okay with adding a `sequence->stream` function and making streams sequences. That does what you describe while also being explicit about what type it's converting to.

**Comment by AlexKnauth** [comment]
Ok thanks!
But also, a `sequence->collection` function doesn't need to be explicit about what type it's converting to, does it? Why couldn't it just return a generic sequence and collection?

**Comment by lexi-lambda** [comment]
Mostly because sequences _can_ be generic, but collections really can't be. The `conj` operator's semantics depend heavily on the actual datatype. It's much harder to abstract over those concepts in a consistent way.

Collections are a very small interface. They are much less about genericism—they're really just an interface for ease of use.

**Comment by AlexKnauth** [comment]
But in the cases where you don't care about the specific semantics of `conj` other than that it adds something somewhere, then it could be implemented much more efficiently if it knows what type of sequence it's dealing with, instead of converting to a stream and then using `stream-cons`. It would need some concrete implentation, yes, but that could be generated on the fly based on the type of sequence. And the fallback could be a wrapper that uses append and wraps the result.

**Comment by lexi-lambda** [comment]
Oh, so you're implying having `sequence->collection` being part of `gen:sequence`? That could work.

**Comment by AlexKnauth** [comment]
Yes. But with a fallback to append so that they don't have to implement it.

**Comment by AlexKnauth** [comment]
I meant fallback to a wrapper implementation that uses append and re-wraps.
